apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
      spec:
        containers:
          - name: mongodb
            image: mongo 
            ports:
            - name: mongo
              containerPorts: 27017
