apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongodb
    role: service
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb    
