apiVersion: v1
kind: ReplicationController
metadata:
  name: rocketchat-controller
  labels:
    app: rocketchat
    role: controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
       app: rocketchat
    spec:
      containers:
        - name: rocketchat
          env:
          - name: MONGO_URL
            value: mongodb://mongo-service:27017/rocketchat
          - name: ROOT_URL
            value: http://caxias.dcc.ufrj.br
          image: rocket.chat
          ports:
            - containerPort: 3000
