apiVersion: v1
kind: ReplicationController
metadata:
  name: rocketchat-controller
  labels:
    app: rocketchat
    role: controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
       app: rocketchat
    spec:
      containers:
        - name: rocketchat
          image: rocket.chat
          ports:
          - containerPort: 3000
