apiVersion: v1
kind: Service
metadata:
  name: rocketchat-service
  labels:
    app: rocketchat
    role: service
spec:
  type: LoadBalancer
  deprecatedPublicIps:
  - "146.164.41.7"
  - "146.164.41.8"
  ports:
  - name: http
    port: 80
  selector:
    app: rocketchat    
